sudo: required

language: node_js

node_js:
  - "10"

cache:
  directories:
    - node_modules

jobs:
  include:
    - env:
        - job=lint
      script: npm run lint
    - env:
        - job=build
      script:
      - npm ci
      - npm run build
    - env:
        - job=test
      script: npm run test