sudo: required

language: node_js

node_js:
  - "16"

before_install:
  # Repo for Yarn
  - sudo apt-key adv --keyserver pgp.mit.edu --recv D101F7899D41F3C3
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn

# keep the yarn cache around to speed up installs  
cache:
  directories:
    - $HOME/.yarn-cache

jobs:
  include:
    - env:
        - job=lint
      script: yarn run lint
    - env:
        - job=licence
      script: yarn run licence-check
    - env:
        - job=build
      script:
        - export NODE_OPTIONS=--max_old_space_size=8192;
        - yarn ci
        - yarn run build
    - env:
        - job=test
      script: yarn run test
