########################################################
############   AUTHENTICATION SETTINGS   ###############
########################################################
authentication:
  use_authent: true
  force_connect: false
  use_discovery: true
  issuer: https://arlas-cloud-dev.eu.auth0.com/
  client_id: TrAfmjESYNWrikvK1d7RPnc5Uve7WJqs
  redirect_uri: http://localhost:4200/callback
  scope: "openid profile"
  silent_refresh_redirect_uri: http://localhost:4200/silent-refresh.html
  require_https: true
  response_type: "id_token token"
  silent_refresh_timeout: 10000
  timeout_factor: 0.75
  session_checks_enabled: true
  clear_hash_after_login: true
  disable_at_hash_check: false
  show_debug_information: true
  logout_url: https://arlas-cloud-dev.eu.auth0.com/v2/logout?returnTo=http://localhost:4200
  storage: sessionstorage
########################################################
############   Persistence SETTINGS   ##################
########################################################
persistence:
  url: 'http://localhost:19997/arlas-persistence-server'
########################################################
############   Permissions SETTINGS   ##################
########################################################
permission:
  url: 'http://localhost:19996/arlas-permissions-server'
########################################################
############   URLs to WUI app   #######################
########################################################
arlas_wui_url: "http://localhost:4200"
links: [ { "icon": "lock", "name": "Google", "url": "http://www.google.com" }, { "icon": "public", "name": "Yahoo", "url": "http://www.yahoo.com" } ]
basemaps: 
  - name: "Basic"
    url: "https://api.maptiler.com/maps/basic/style.json?key=YOUR_KEY"
    image: "https://cloud.maptiler.com/static/img/maps/basic.png"
  - name: "Bright"
    url: "https://api.maptiler.com/maps/bright/style.json?key=YOUR_KEY"
    image: "https://cloud.maptiler.com/static/img/maps/bright.png"
  - name: "Streets"
    url: "https://api.maptiler.com/maps/streets/style.json?key=YOUR_KEY"
    image: "https://cloud.maptiler.com/static/img/maps/streets.png"

