########################################################
############   AUTHENTICATION SETTINGS   ###############
########################################################
authentication:
  use_authent: true
  force_connect: false
  use_discovery: true
  issuer: https://arlas-cloud-abc.eu.auth0.com/
  client_id: 9mIJ966gS95riVkYJESrudLEq3D5S2os
  scope: "openid profile"
  require_https: true
  response_type: "id_token token"
  silent_refresh_timeout: 5000
  timeout_factor: 0.75
  session_checks_enabled: true
  clear_hash_after_login: false
  disable_at_hash_check: false
persistence:
  url: 'http://localhost:19997/arlas_persistence_server'
